# Generated by Django 3.1.3 on 2020-11-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('bsb', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('signup_date', models.DateTimeField(verbose_name='publish date')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('bsb', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='publish date')),
                ('pay_date', models.DateTimeField(verbose_name='pay date')),
                ('status', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_payer.company')),
            ],
        ),
    ]
