# Generated by Django 3.1.3 on 2020-11-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_payer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='account',
            new_name='account_num',
        ),
    ]
