# Generated by Django 3.1.3 on 2020-11-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_payer', '0002_auto_20201125_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='account',
            new_name='account_num',
        ),
    ]
