# Generated by Django 3.1.3 on 2020-11-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_payer', '0003_auto_20201125_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pay_date',
        ),
    ]
