# Generated by Django 3.1.3 on 2020-12-02 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_payer', '0004_auto_20201130_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2120, 11, 8, 13, 26, 37, 252514), verbose_name='paid date'),
        ),
    ]
